/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controldenotas;
//import javax.swing.JOptionPane;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author ernes
 */
public class ControlDeNotasJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ControlDeNotasJFrame
     */
    public ControlDeNotasJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        lbCarrera = new javax.swing.JLabel();
        cbCarrera = new javax.swing.JComboBox<>();
        lbCiclo = new javax.swing.JLabel();
        lbCUM = new javax.swing.JLabel();
        tfCUM = new javax.swing.JTextField();
        cbCiclo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbMateria1 = new javax.swing.JComboBox<>();
        lbMateria = new javax.swing.JLabel();
        cbMateria2 = new javax.swing.JComboBox<>();
        cbMateria3 = new javax.swing.JComboBox<>();
        cbMateria4 = new javax.swing.JComboBox<>();
        cbMateria5 = new javax.swing.JComboBox<>();
        lbUV = new javax.swing.JLabel();
        cbUVMateria1 = new javax.swing.JComboBox<>();
        cbUVMateria2 = new javax.swing.JComboBox<>();
        cbUVMateria3 = new javax.swing.JComboBox<>();
        cbUVMateria4 = new javax.swing.JComboBox<>();
        cbUVMateria5 = new javax.swing.JComboBox<>();
        lbNota = new javax.swing.JLabel();
        tfNotaMateria1 = new javax.swing.JTextField();
        tfNotaMateria2 = new javax.swing.JTextField();
        tfNotaMateria3 = new javax.swing.JTextField();
        tfNotaMateria4 = new javax.swing.JTextField();
        tfNotaMateria5 = new javax.swing.JTextField();
        lbEstadoCiclo = new javax.swing.JLabel();
        lbEstadoMateria1 = new javax.swing.JLabel();
        lbEstadoMateria2 = new javax.swing.JLabel();
        lbEstadoMateria3 = new javax.swing.JLabel();
        lbEstadoMateria4 = new javax.swing.JLabel();
        lbEstadoMateria5 = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        lbMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setText("CONTROL DE NOTAS");

        lbNombre.setText("Nombre:");

        lbCarrera.setText("Carrera:");

        cbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la carrera", "Ing. Sistemas", "Ing. Industrial", "Ing. Electrica", "Ing. Agronegocios" }));

        lbCiclo.setText("Ciclo:");

        lbCUM.setText("CUM");

        cbCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el ciclo", "Ciclo 01", "Ciclo 02" }));
        cbCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCicloActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controldenotas/logou.jpeg"))); // NOI18N

        cbMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materia 1", "Bases de Datos II", "Desarrollo de Software I", "Electronica", "Investigacion de Operaciones I", "Legislacion Aplicada a la Empresa", " " }));

        lbMateria.setText("Materia");

        cbMateria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materia 2", "Bases de Datos II", "Desarrollo de Software I", "Electronica", "Investigacion de Operaciones I", "Legislacion Aplicada a la Empresa" }));

        cbMateria3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materia 3", "Bases de Datos II", "Desarrollo de Software I", "Electronica", "Investigacion de Operaciones I", "Legislacion Aplicada a la Empresa" }));

        cbMateria4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materia 4", "Bases de Datos II", "Desarrollo de Software I", "Electronica", "Investigacion de Operaciones I", "Legislacion Aplicada a la Empresa" }));

        cbMateria5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materia 5", "Bases de Datos II", "Desarrollo de Software I", "Electronica", "Investigacion de Operaciones I", "Legislacion Aplicada a la Empresa" }));

        lbUV.setText("UV");

        cbUVMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UV", "3", "4" }));

        cbUVMateria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UV", "3", "4" }));

        cbUVMateria3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UV", "3", "4" }));
        cbUVMateria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUVMateria3ActionPerformed(evt);
            }
        });

        cbUVMateria4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UV", "3", "4" }));
        cbUVMateria4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUVMateria4ActionPerformed(evt);
            }
        });

        cbUVMateria5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UV", "3", "4" }));

        lbNota.setText("Nota");

        tfNotaMateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNotaMateria1ActionPerformed(evt);
            }
        });

        lbEstadoCiclo.setText("Estado");

        lbEstadoMateria1.setText("Estado");

        lbEstadoMateria2.setText("Estado");

        lbEstadoMateria3.setText("Estado");

        lbEstadoMateria4.setText("Estado");

        lbEstadoMateria5.setText("Estado");

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        lbMensaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMensaje.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btCalcular)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbMateria5, 0, 1, Short.MAX_VALUE)
                                            .addComponent(cbMateria4, 0, 1, Short.MAX_VALUE)
                                            .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbMateria3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(cbUVMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbUVMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbUVMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(cbUVMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(cbUVMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNotaMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNotaMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNotaMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNotaMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNotaMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lbUV)
                                                    .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(lbCarrera)
                                                .addGap(49, 49, 49)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lbCiclo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbCUM)
                                            .addComponent(tfCUM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(lbMateria)
                                        .addGap(217, 217, 217)
                                        .addComponent(lbNota)))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEstadoMateria1)
                                    .addComponent(lbEstadoMateria5)
                                    .addComponent(lbEstadoMateria4)
                                    .addComponent(lbEstadoMateria3)
                                    .addComponent(lbEstadoMateria2)
                                    .addComponent(lbEstadoCiclo)))
                            .addComponent(lbMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCiclo)
                    .addComponent(lbCUM)
                    .addComponent(lbNombre)
                    .addComponent(lbCarrera))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMateria)
                            .addComponent(lbUV)
                            .addComponent(lbNota)
                            .addComponent(lbEstadoCiclo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUVMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNotaMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstadoMateria1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUVMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNotaMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstadoMateria2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUVMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNotaMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstadoMateria3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUVMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNotaMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstadoMateria4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUVMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNotaMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstadoMateria5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNotaMateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNotaMateria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNotaMateria1ActionPerformed

    private void cbUVMateria4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUVMateria4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUVMateria4ActionPerformed

    private void cbUVMateria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUVMateria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUVMateria3ActionPerformed

    private void cbCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCicloActionPerformed

// Función para verificar si una cadena es numérica
private boolean esNumero(String str) {
    return str.matches("-?\\d+(\\.\\d+)?");
}

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        // TODO add your handling code here:
int contadorMateriasAprobadas = 0;
int contadorMateriasReprobadas = 0;
double calculoCUM = 0.0;
String CUM = "";
String carrera = "";
String cicloActual = "";
String unidadesValorativas = "";
String materias = "";
String nombre = "";
String notas = "";

String carreraSeleccionada = (String) this.cbCarrera.getSelectedItem();
String cicloSeleccionado = (String) this.cbCiclo.getSelectedItem();
String UVMat1 = (String) this.cbUVMateria1.getSelectedItem();
String UVMat2 = (String) this.cbUVMateria2.getSelectedItem();
String UVMat3 = (String) this.cbUVMateria3.getSelectedItem();
String UVMat4 = (String) this.cbUVMateria4.getSelectedItem();
String UVMat5 = (String) this.cbUVMateria5.getSelectedItem();
String Materia1 = (String) this.cbMateria1.getSelectedItem();
String Materia2 = (String) this.cbMateria2.getSelectedItem();
String Materia3 = (String) this.cbMateria3.getSelectedItem();
String Materia4 = (String) this.cbMateria4.getSelectedItem();
String Materia5 = (String) this.cbMateria5.getSelectedItem();

//Validacion de unidades valorativas
if("UV".equals(UVMat1) || "UV".equals(UVMat2) || "UV".equals(UVMat3)
   || "UV".equals(UVMat4) || "UV".equals(UVMat5)){
unidadesValorativas = "-1";
JOptionPane.showMessageDialog(this,"Seleccione las Unidades Valorativas.","Error",JOptionPane.ERROR_MESSAGE);
}

//Validacion de las materia
if("Materia1".equals(Materia1) || "Materia2".equals(Materia2) 
   || "Materia3".equals(Materia3) || "Materia4".equals(Materia4) 
   || "Materia5".equals(Materia5)){
materias = "-1";
JOptionPane.showMessageDialog(this,"Seleccione las Materias.","Error",JOptionPane.ERROR_MESSAGE);
}

//Validación del nombre
if(this.tfNombre.getText().isEmpty()){
nombre = "-1";
JOptionPane.showMessageDialog(this,"El campo del nombre no debe quedar vacío.","Error",JOptionPane.ERROR_MESSAGE);
}

//Validacion opcion por defecto del ciclo
if("Seleccione el ciclo".equals(cicloSeleccionado)){
cicloActual = "-1";
JOptionPane.showMessageDialog(this,"Seleccione el ciclo.","Error",JOptionPane.ERROR_MESSAGE);
}

//Validacion opcion por defecto de la carrera
if("Seleccione la carrera".equals(carreraSeleccionada)){
carrera = "-1";
JOptionPane.showMessageDialog(this,"Seleccione una carrera.","Error",JOptionPane.ERROR_MESSAGE);
}
        

// Variables para guardar las notas para validar el ingreso de numeros
String inputMateria1 = this.tfNotaMateria1.getText();
String inputMateria2 = this.tfNotaMateria2.getText();
String inputMateria3 = this.tfNotaMateria3.getText();
String inputMateria4 = this.tfNotaMateria4.getText();
String inputMateria5 = this.tfNotaMateria5.getText();

if(this.tfNotaMateria1.getText().isEmpty() || this.tfNotaMateria2.getText().isEmpty() ||
   this.tfNotaMateria3.getText().isEmpty() || this.tfNotaMateria4.getText().isEmpty() ||
   this.tfNotaMateria5.getText().isEmpty()){
   notas = "-1";
   JOptionPane.showMessageDialog(this, "Los campos de las materias no pueden quedar vacíos.", "Error", JOptionPane.ERROR_MESSAGE);
}
else if (esNumero(inputMateria1) && esNumero(inputMateria2) && esNumero(inputMateria3) && esNumero(inputMateria4) && esNumero(inputMateria5)) {
    // Convertir las entradas a double si son números
    double NotaMateria1 = Double.parseDouble(inputMateria1);
    double NotaMateria2 = Double.parseDouble(inputMateria2);
    double NotaMateria3 = Double.parseDouble(inputMateria3);
    double NotaMateria4 = Double.parseDouble(inputMateria4);
    double NotaMateria5 = Double.parseDouble(inputMateria5);

    //Variables para guardar las UV en un tipo que se pueda usar para el calculo 
    double UVMateria1 = Double.parseDouble((String) cbUVMateria1.getSelectedItem());
    double UVMateria2 = Double.parseDouble((String) cbUVMateria2.getSelectedItem());
    double UVMateria3 = Double.parseDouble((String) cbUVMateria3.getSelectedItem());
    double UVMateria4 = Double.parseDouble((String) cbUVMateria4.getSelectedItem());
    double UVMateria5 = Double.parseDouble((String) cbUVMateria5.getSelectedItem());
        
        //Calculo del CUM
        calculoCUM = ((NotaMateria1*UVMateria1) + (NotaMateria2*UVMateria2) +
        (NotaMateria3*UVMateria3) + (NotaMateria4*UVMateria4) + (NotaMateria5*UVMateria5))
        / (UVMateria1 + UVMateria2 + UVMateria3 + UVMateria4 + UVMateria5);
        
        // Creamos un objeto DecimalFormat para formatear el número con 1 decimal
        DecimalFormat df = new DecimalFormat("#.#");
        CUM = df.format(calculoCUM);
        tfCUM.setText(CUM);
        // Hacer que el TextField no sea editable
        tfCUM.setEditable(false);
        
        //Calcular las materias aprobadas y reprobadas
        if(NotaMateria1>=6){
           lbEstadoMateria1.setText("Aprobada");
           contadorMateriasAprobadas++;
        }else{
           lbEstadoMateria1.setText("Reprobada");
           contadorMateriasReprobadas++;
        }
        if(NotaMateria2>=6){
           lbEstadoMateria2.setText("Aprobada");
           contadorMateriasAprobadas++;
        }else{
           lbEstadoMateria2.setText("Reprobada");
           contadorMateriasReprobadas++;
        }
        if(NotaMateria3>=6){
           lbEstadoMateria3.setText("Aprobada");
           contadorMateriasAprobadas++;
        }else{
           lbEstadoMateria3.setText("Reprobada");
           contadorMateriasReprobadas++;
        }
        if(NotaMateria4>=6){
           lbEstadoMateria4.setText("Aprobada");
           contadorMateriasAprobadas++;
        }else{
           lbEstadoMateria4.setText("Reprobada");
           contadorMateriasReprobadas++;
        }
        if(NotaMateria5>=6){
           lbEstadoMateria5.setText("Aprobada");
           contadorMateriasAprobadas++;
        }else{
           lbEstadoMateria5.setText("Reprobada");
           contadorMateriasReprobadas++;
        }
        
}else{
    JOptionPane.showMessageDialog(this, "Ingresó un valor no numérico en las notas.", "Error", JOptionPane.ERROR_MESSAGE);
}

//Mostrar el mensaje si los campos son distinto de -1
if(!"-1".equals(cicloActual) && !"-1".equals(carrera) && !"-1".equals(nombre)
   && !"-1".equals(unidadesValorativas) && !"-1".equals(materias) && !"-1".equals(notas)){
        lbMensaje.setText("<html>" + this.tfNombre.getText() + " su estado actual es de "
        + contadorMateriasAprobadas + " materias aprobadas y "
        + contadorMateriasReprobadas + " reprobadas.<br> Su CUM actual del ciclo es "
        + CUM +".</html>");
}
    }//GEN-LAST:event_btCalcularActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlDeNotasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlDeNotasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlDeNotasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlDeNotasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlDeNotasJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JComboBox<String> cbCarrera;
    private javax.swing.JComboBox<String> cbCiclo;
    private javax.swing.JComboBox<String> cbMateria1;
    private javax.swing.JComboBox<String> cbMateria2;
    private javax.swing.JComboBox<String> cbMateria3;
    private javax.swing.JComboBox<String> cbMateria4;
    private javax.swing.JComboBox<String> cbMateria5;
    private javax.swing.JComboBox<String> cbUVMateria1;
    private javax.swing.JComboBox<String> cbUVMateria2;
    private javax.swing.JComboBox<String> cbUVMateria3;
    private javax.swing.JComboBox<String> cbUVMateria4;
    private javax.swing.JComboBox<String> cbUVMateria5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbCUM;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbCiclo;
    private javax.swing.JLabel lbEstadoCiclo;
    private javax.swing.JLabel lbEstadoMateria1;
    private javax.swing.JLabel lbEstadoMateria2;
    private javax.swing.JLabel lbEstadoMateria3;
    private javax.swing.JLabel lbEstadoMateria4;
    private javax.swing.JLabel lbEstadoMateria5;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JLabel lbMensaje;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNota;
    private javax.swing.JLabel lbUV;
    private javax.swing.JTextField tfCUM;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNotaMateria1;
    private javax.swing.JTextField tfNotaMateria2;
    private javax.swing.JTextField tfNotaMateria3;
    private javax.swing.JTextField tfNotaMateria4;
    private javax.swing.JTextField tfNotaMateria5;
    // End of variables declaration//GEN-END:variables
}
